# Generated by hyperi-rustlib deployment module
# Do not edit manually — regenerate from DeploymentContract
#
# License:   FSL-1.1-ALv2
# Copyright: (c) 2026 HYPERI PTY LIMITED

FROM ubuntu:24.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates curl netcat-openbsd iputils-ping \
    && rm -rf /var/lib/apt/lists/*

COPY dfe-transform-vector /usr/local/bin/dfe-transform-vector
RUN chmod +x /usr/local/bin/dfe-transform-vector

RUN useradd --create-home --uid 1000 appuser

# Vector binary (built/downloaded externally by CI)
COPY vector /usr/local/bin/vector

# Vector data and config directories
RUN mkdir -p /var/lib/vector /var/run/vector/config /etc/dfe/transforms \
    && chown -R appuser:appuser /var/lib/vector /var/run/vector /etc/dfe

USER appuser

EXPOSE 9090 9000 8686

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD curl -sf http://localhost:9090/health/live > /dev/null || exit 1

ENTRYPOINT ["dfe-transform-vector"]
CMD ["--config", "/etc/dfe/config.yaml"]

