# Project:   dfe-transform-vector
# File:      Dockerfile
# Purpose:   production container image
#
# License:   FSL-1.1-ALv2
# Copyright: (c) 2026 HYPERI PTY LIMITED
#
# AUTOGENERATED — do not edit by hand.
# Generated by hyperi-rustlib::deployment::generate_dockerfile()
# Schema version: 2
# Source contract: dfe-transform-vector::deployment::contract()
# Regenerate with: `dfe-transform-vector emit-dockerfile > Dockerfile`

FROM ubuntu:24.04

LABEL io.hyperi.profile="production"

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates curl netcat-openbsd iputils-ping \
    && rm -rf /var/lib/apt/lists/*

COPY dfe-transform-vector /usr/local/bin/dfe-transform-vector
RUN chmod +x /usr/local/bin/dfe-transform-vector

# Ubuntu 24.04 ships with ubuntu user at UID 1000 — remove before creating appuser
RUN userdel -r ubuntu && useradd --create-home --uid 1000 appuser
USER appuser

EXPOSE 9090 9000 8686

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD curl -sf http://localhost:9090/health/live > /dev/null || exit 1

ENTRYPOINT ["dfe-transform-vector"]
CMD ["--config", "/etc/dfe/config.yaml"]

