apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dfe-transform-vector.fullname" . }}-config
  labels:
    {{- include "dfe-transform-vector.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
