apiVersion: v1
kind: Service
metadata:
  name: {{ include "dfe-transform-vector.fullname" . }}
  labels:
    {{- include "dfe-transform-vector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: 8686
      targetPort: 8686
      protocol: TCP
      name: vector-api
    {{- if eq (default "bus" ((.Values.config).source).transport) "direct" }}
    - port: {{ .Values.service.pushPort | default 6000 }}
      targetPort: push
      protocol: TCP
      name: push
    {{- end }}
  selector:
    {{- include "dfe-transform-vector.selectorLabels" . | nindent 4 }}
