apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kafka-sasl-secret
spec:
  refreshPolicy: Periodic
  refreshInterval: 15m
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    name: kafka-sasl-secret
    template:
      metadata:
        annotations:
          reloader.stakater.com/auto: "true"
          stakater-reloader-target: "kafka-sasl-secret"
  dataFrom:
    - extract:
        key: "AmazonMSK_test_vector_msk_auth"
      rewrite:
        - regexp:
            source: "bootstrap_servers_sasl_scram"
            target: "KAFKA_BROKERS_SASL_SCRAM"
        - regexp:
            source: "username"
            target: "KAFKA_SASL_USERNAME"
        - regexp:
            source: "password"
            target: "KAFKA_SASL_PASSWORD"
