apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-kafka-credential
spec:
  env:
  - parameter: bootstrapServers
    name: KAFKA_BROKERS_SASL_SCRAM
    containerName: dfe-transform-vector
  secretTargetRef:
  - parameter: username
    name: kafka-sasl-secret
    key: KAFKA_SASL_USERNAME
  - parameter: password
    name: kafka-sasl-secret
    key: KAFKA_SASL_PASSWORD
